development:
  adapter: postgresql
  encoding: unicode
  database: epuka_development
  pool: 5
  username: banta
  password: denmark
test:
  adapter: postgresql
  encoding: unicode
  database: epuka_test
  pool: 5
  username: banta
  password: denmark

production:
  adapter: postgresql
  encoding: unicode
  database: epuka_production
  pool: 5
  username: banta
  password: denmark
